### ISSUE TITLE
Kafka: Liveness probe fails after rebalance took place

### ISSUE THREAD

**Issue by spike83** [smallrye/smallrye-reactive-messaging#1259] opened 2021-06-14 14:00 UTC
I'm using quarkus 2.0.0.CR3 and therefore smallrye kafka 3.3.2

Consuming a high velocity stream with multiple consumers in a group.
Using `commit-strategy: throttled`

Incoming channel is annotated like this:
```
  @Incoming("events")
  @Blocking
  @Acknowledgment(Strategy.MANUAL)
```
In here I have some async operation (Elasticsearch BulkPorcessor) etc. which ack / nacks the messages.

When a new consumer joins on the others I get

`SRMSG18239: Acked record 8041153253 on group 'group' was ignored because the topic partition 'topic-4' was revoked for this instance. Record will likely be processed again.`

I'm ok with some duplicates, so far so good.

After a few seconds on the next livenes check I get

`SRHCK01001: Reporting health down status: {"status":"DOWN","checks":[{"name":"SmallRye Reactive Messaging - liveness check","status":"DOWN","data":{"events":"[KO] - Too Many Messages without acknowledgement in topic topic (partition:4), last committed offset is 7980556233Too Many Messages without acknowledgement in topic topic (partition:7), last committed offset is 7868958352"}}]}`

I cannot see any other errors or nacked messages. It looks like the messages which are acked from the aync operation after the rebalance took place count into the number causing 'Too Many Messages without acknowledgement' and cause the liveness to get down. Eventually they are also leaking memory.

Am I doing something wrong?
Is there a way to get rid of these messages which are acked on a revoked partition?

**Comment by cescoffier** [comment] 2021-06-14 14:01
Hum, that's definitely a bug, the failure should not be "fatal".

**Comment by cescoffier** [comment] 2021-06-14 14:02
Oh, I got it, when we rebalance we should clear the message queue waiting for acknowledgment. I'm surprised because I was sure it was done. anyway, that's a bug.

**Comment by Ladicek** [comment] 2021-06-14 14:12
Should we clear the entire queue, or just remove messages that belong to partitions we no longer consume?

Just curious -- I'm not totally sure what's best (or correct, FWIW).

**Comment by cescoffier** [comment] 2021-06-14 14:14
Yes, that's the idea. 
Removing the message that can't be committed anyway.

**Comment by cescoffier** [comment] 2021-06-14 14:14
I need to refresh my memory, but I vaguely remember that the queue is actually a map per partition

**Comment by cescoffier** [comment] 2021-06-14 14:32
Hum, I may found the problem: https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/commit/KafkaThrottledLatestProcessedCommit.java#L139 ?

That seems to be something introduced with the new Kafka client. I need to double-check which set of partitions we get.

**Comment by cescoffier** [comment] 2021-06-14 14:34
No, it seems ok, we get the "The list of partitions that were assigned to the consumer and now need to be revoked (may not include all currently assigned partitions)"

**Comment by cescoffier** [comment] 2021-06-15 06:07
Just a head's up. I was unable to reproduce it with a real setup, but, I was able to reproduce it with a mock consumer. A fix is coming...

**Closed** 2021-06-15 16:30 UTC
Labels: bug, kafka
