### ISSUE TITLE
Kafka DNS issue recovery

### ISSUE THREAD

**Issue by FreifeldRoyi** [smallrye/smallrye-reactive-messaging#376] opened 2020-01-16 12:30 UTC
Hi guys,  
I got a `java.net.UnknownHostException` from `java.net.Inet4AddressImpl.lookupAllHostAddr` after a few days of regular run of my service. 
I use Quarkus 1.1.1.Final with Kafka reactive messaging.
We feel like we experienced a glitch in the DNS that caused the service to buffer messages and (eventually) crash. 
Locally, when Kafka docker is not up, I'm used to get something like ` (kafka-producer-network-thread | producer-3) [Producer clientId=producer-3] Connection to node 1001 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.{}` but there were no logs of this sort.

The current reactive producer is set up the following way:
```
    @Incoming("in")
    @Outgoing("to-kafka")
    public Flowable<KafkaMessage<String, String>> toKafka(Flowable<Message<List<JsonObject>>> inputs) {
        return inputs
                .flatMapIterable(Message::getPayload)
                .map(s -> KafkaMessage.of(<do something with s>))
                .onBackpressureDrop(message -> {
                    LOGGER.trace("message failed: " + message.getPayload());
                    <send-fail-metrics>
                })
                .doOnNext(message -> <send-success-metrics>);
    }
```

Is the reconnect should kick in if the DNS resolve failed? 
What do you suggest I do in order to keep the service alive? I thought about adding _doOnError_ but I'm not sure if it will help in this case.

Thank you

**Comment by cescoffier** [comment] 2020-01-17 11:06
`doOnError` would let you log an error, but here it seems to be tricky. I don't believe there is a way to "re-resolved" the broken DNS name until the cache expired. 

Right now, it should print something like:

```
LOGGER.error("Message {} was not sent to Kafka topic '{}'", message, record.topic(),
                                        ar.cause());
future.completeExceptionally(ar.cause());
```

Did you see this message?

**Comment by FreifeldRoyi** [comment] 2020-01-19 09:32
No.
These are the exceptions I got:
- Many IOExceptions with exception.message - `No file descriptors available` and a message `An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.`

- 2 VertxException with exception.message `Thread blocked` and message `Thread Thread[vert.x-eventloop-thread-0,5,main]=Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3081 ms, time limit is 2000 ms`

- 1 UnknownHostException with exception.message `<my kafka url>: System error` and message
`[Producer clientId=producer-1] Error connecting to node <my kafka url>`

**Comment by tqvarnst** [comment] 2020-02-13 17:03
This is most likely because of a DNS lookup failure in your network and not something that reactive messaging can solve. Since we cannot reproduce this issue, we are going to close it. If you are able to reproduce this issue please re-open it with instructions on how to reproduce.

**Closed** 2020-02-13 17:43 UTC
