### ISSUE TITLE
Multiple @Incomings with RabbitMQ Connector causing "Bean is null"

### ISSUE THREAD

**Issue by jonsalvas** [smallrye/smallrye-reactive-messaging#1938] opened 2022-10-06 13:10 UTC
When using multiple @Incoming annotations over a rabbitmq consumer like this:

```

public class TrackingEventConsumer {

    static final Logger LOG = Logger.getLogger(TrackingEventConsumer.class);


    @Incoming("tracking_events_k1_incoming")
    @Incoming("tracking_events_k2_incoming")
    public CompletionStage<Void> consume(Message<String> message) {
        LOG.debug(String.format("consumed message: %s", message.getPayload()));
        return message.ack();
    }

}
```

with the following config:
```
      incoming:
        tracking_events_k1_incoming:
          connector:
            smallrye-rabbitmq
          exchange:
            name: "x.tracking"
            declare: false
          routing-keys: k1
          queue:
            name: "q.k1"
        tracking_events_k2_incoming:
          connector:
            smallrye-rabbitmq
          exchange:
            name: "x.tracking"
            declare: false
          routing-keys: k2
          queue:
            name: "q.k2"
```

I receive the following error, when starting the quarkus app:

```
2022-10-06 15:09:00,239 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:122)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:144)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:455)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:66)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:150)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:106)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.enterprise.inject.spi.DefinitionException: java.lang.NullPointerException: Bean is null
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager.createMediator(MediatorManager.java:185)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager_Subclass.createMediator$$superforward1(Unknown Source)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager_Subclass$$function$$6.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager_Subclass.createMediator(Unknown Source)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager_ClientProxy.createMediator(Unknown Source)
	at io.smallrye.reactive.messaging.providers.wiring.Wiring$SubscriberMediatorComponent.materialize(Wiring.java:571)
	at io.smallrye.reactive.messaging.providers.wiring.Graph.lambda$materialize$11(Graph.java:105)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at io.smallrye.reactive.messaging.providers.wiring.Graph.materialize(Graph.java:104)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager.start(MediatorManager.java:205)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager_Subclass.start$$superforward1(Unknown Source)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager_Subclass$$function$$14.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager_Subclass.start(Unknown Source)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager_ClientProxy.start(Unknown Source)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:41)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Subclass.onApplicationStart$$superforward1(Unknown Source)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Subclass.onApplicationStart(Unknown Source)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	... 13 more
Caused by: java.lang.NullPointerException: Bean is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at io.quarkus.arc.impl.BeanManagerImpl.getReference(BeanManagerImpl.java:55)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager.createMediator(MediatorManager.java:162)
	... 59 more

```

**Comment by cescoffier** [comment] 2022-10-25 08:01
ping @ozangunalp ?

**Comment by ozangunalp** [comment] 2022-10-26 08:44
@jonsalvas I cannot reproduce this easily. Would you have a reproducer project?

**Comment by ozangunalp** [comment] 2023-12-18 13:30
Closing this, as I can't reproduce and doesn't seem related to rabbitmq after all.

**Closed by ozangunalp** 2023-12-18 13:30 UTC
Labels: bug, rabbitmq
