### ISSUE TITLE
CommitFailed never recovered the connection

### ISSUE THREAD

**Issue by burmanm** [smallrye/smallrye-reactive-messaging#518] opened 2020-04-23 14:25 UTC
We ran into this issue this morning, where the client stopped ingesting messages and never recovered from this issue (no more messages were polled until we restarted Quarkus instance):

```
2020-04-23 01:09:33,229 ERROR [io.sma.rea.mes.kaf.imp.KafkaSource] (vert.x-eventloop-thread-0) Unable to read a record from Kafka topic 'platform.inventory.host-egress': org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.sendOffsetCommitRequest(ConsumerCoordinator.java:1061)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:936)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1387)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1349)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$commit$27(KafkaReadStreamImpl.java:527)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$submitTaskWhenStarted$3(KafkaReadStreamImpl.java:127)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-04-23 01:09:38,309 INFO  [org.apa.kaf.cli.con.int.ConsumerCoordinator] (vert.x-kafka-consumer-thread-0) [Consumer clientId=consumer-correlation-1, groupId=correlation] Failing OffsetCommit request since the consumer is not part of an active group
```

**Comment by erard22** [comment] 2020-06-16 12:15
I faced the same issue with Quarkus and it is simple to reproduce with the kafka-quickstart example. Changing the code so that it throws an exception and the consumer stops consuming messages: 

```
    private int counter = 0;

    @Incoming("kafka")
    public CompletionStage<Void> consume(KafkaRecord<String, String> message) {
        String payload = message.getPayload();
        String key = message.getKey();
        Headers headers = message.getHeaders();
        int partition = message.getPartition();
        Instant timestamp = message.getTimestamp();
        System.out.println("received: " + payload + " from topic " + message.getTopic());

        counter++;

        if (counter % 2 == 0) {
            System.out.println("Odd message, throwing RuntimeException");
            throw new RuntimeException("Message number " + counter);
        }

        return message.ack();
    }
```

**Comment by cescoffier** [comment] 2020-06-16 13:53
That is now fixed in master. It would nack the Kafka message and you can decide what you do with it (continue, write the record to a dead letter queue, fail-stop (default))

**Comment by erard22** [comment] 2020-06-17 16:50
yeah I see. It also works with a simpler interface.

```
    @Incoming("kafka")
    public void consume(String payload) {
        System.out.println("received: " + payload);
        doSomethingThatMightThrowAnException(payload);
    }
```

So with Quarkus we need a version that uses the next version of this implementation.

**Comment by cescoffier** [comment] 2020-06-18 09:26
Ths update just got merged.

Le mer. 17 juin 2020 à 18:50, Michel Erard <notifications@github.com> a
écrit :

**Closed** 2020-06-23 13:02 UTC

**Comment by erard22** [comment] 2020-06-24 11:38
After comparing my tests why this is working in smallrye and not in quarkus I found the reason: OMG, my test was wrong. (nearly 20 years of Java and still doing errors)

So using a simple interface like this: 

    @Incoming("kafka")
    public void consume(String payload) {
        System.out.println("received: " + payload);
        doSomethingThatMightThrowAnException(payload);
    }

and the processing does not recover after the first thrown exception. I would assume that the framework would handle this under the hood and return a `nack`.

Could we reopen the issue?

**Comment by cescoffier** [comment] 2020-06-24 11:51
are you using the latest SR Reactive Messaging? Which failure handling strategy are you using? 
See https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2.1/kafka/kafka.html#_failure_management.

**Comment by erard22** [comment] 2020-06-24 13:52
I have it on `ignore`

`mp.messaging.incoming.kafka.failure-strategy=ignore`

Shouldn't there also be a strategy that triggers a resend by kafka

**Comment by cescoffier** [comment] 2020-06-24 14:24
Ignore will just skip the record. You can use a dead letter queue targeting
the same topic. But you are right we don’t have a retry per se.
