### ISSUE TITLE
How to propagate JTA state?

### ISSUE THREAD

**Issue by stphngrtz** [smallrye/smallrye-reactive-messaging#1016] opened 2021-02-18 12:56 UTC
I would like to propagate JTA state (= the transaction) between a transactional REST endpoint that emits a message to a reactive-messaging connector.

```
@Inject
@Channel("test")
Emitter<String> emitter;

@POST
@Transactional
public Response test() {
    emitter.send("test");
}
```

and

```
@ApplicationScoped
@Connector("test")
public class TestConnector implements OutgoingConnectorFactory {

    @Inject
    TransactionManager tm;

    @Override
    public SubscriberBuilder<? extends Message<?>, Void> getSubscriberBuilder(Config config) {
        return ReactiveStreams.<Message<?>>builder()
            .flatMapCompletionStage(message -> {
                tm.getTransaction(); // = null
                return message.ack();
            })
            .ignore();
    }
}
```

As I understand, context-propagation is responsible for making the transaction available (see `io.smallrye.context.jta.context.propagation.JtaContextProvider#currentContext`). The problem seems to be, that `currentContext` gets created on subscription, which happens when the injection point (`Emitter<String> emitter`) get its instance. Which is too early to properly capture the transaction.

What am I missing?

By the way, I am having the same problem when using `@Incoming` / `@Outgoing` instead of the emitter. I have decided to give you this example because it is easy to understand and reproduce.

FYI: asked the same question at SO (https://stackoverflow.com/questions/66260352/how-to-propagate-jta-state-when-using-reactive-messaging)

**Comment by cescoffier** [comment] 2021-02-19 07:23
Unfortunately, there is no direct support for this. 
To pass the transaction, use:

```
emitter.send(Message.of("test").addMetadata(getTransaction()));
```

and in the consumer method:

```
@Incoming(...)
public CompletionStage<Void> consume(Message<String> m) {
   Optional<Transaction> tx = m.getMetadata(Transaction.class);
   // ...
   return m.ack();
}
```


However, because your transaction is bound to the request scope, the transaction is terminated when the endpoint produces a result, and so not when the consumer method does something with it. You would need to transform your endpoint to be asynchronous (return a CompletionStage or a Uni) and only produce the result when the emitted `Message` is acknowledged. To receive a notification you would need:

```
return Uni.createFrom().emitter(uni -> {
   emitter.send(Message.of("test")
      .addMetadata(getTransaction())
      .withAck(() -> {
         uni.complete(null);
         return CompletableFuture.completed(null);
      }
      .withNack(failure -> {
         uni.fail(failure);
         return CompletableFuture.completed(null);
      }
      ;
}
```

**Comment by stphngrtz** [comment] 2021-02-19 09:00
I am not trying to pass the transaction from producer to consumer. The problem I am describing is between resource and outgoing connector.

```
+-------------------------------------------+       +--------------------------------------------------+
|                                           |       |                                                  |
|                 Producer                  |       |                     Consumer                     |
|                                           |       |                                                  |
| +----------+       +--------------------+ |       | +--------------------+       +-----------------+ |
| |          |       |                    | |       | |                    |       |                 | |
| | Resource | +---> | Outgoing Connector | | +---> | | Incoming Connector | +---> | Message Handler | |
| |          |       |                    | |       | |                    |       |                 | |
| +----------+       +--------------------+ |       | +--------------------+       +-----------------+ |
|                                           |       |                                                  |
+-------------------------------------------+       +--------------------------------------------------+
```

I have provided a reproducer for you: https://github.com/stphngrtz/smallrye-reactive-messaging-issue-1016

**Comment by cescoffier** [comment] 2021-02-19 09:06
Do you mean over the network? If that's the case it's not supported.

**Comment by cescoffier** [comment] 2021-02-19 09:11
Regarding the reproducer, it's what I described above. The `emitter` must send a `Message` with the transaction in the metadata of the message. The connector can retrieve the Transaction from the `Message`.

However, as said above, be careful of the lifecycle as the transaction is generally discarded when the request scope is terminated.

**Comment by stphngrtz** [comment] 2021-02-19 09:26
Within the same JVM, not over the network. I am just trying to propagate the transaction from the REST resource (using emitter, reactive messaging API) to the outgoing connector (API implementation that is supposed to actually send the message).

If I have to do this manually via metadata, whats the point of having context propagation? I mean, [this](https://github.com/smallrye/smallrye-context-propagation/blob/master/jta/src/main/java/io/smallrye/context/jta/context/propagation/JtaContextProvider.java) looks exactly like what I want. The only problem is, that the transaction gets _captured_ on subscription, when the transaction is not yet active. If it would get _captured_ on send, then it would work. Maybe my understanding of context propagation is wrong but I can't come up with any scenario related to messaging in which "on subscription" is the right time to capture the JTA context.

**Comment by cescoffier** [comment] 2021-02-19 09:44
There are some cases, but yes, at the moment using the context propagation with the emitter is not working as most people would expect. 

We had worked on a better integration (capturing the context during the emission, and adding the context to the metadata automatically), but it was not mature enough and we rolled back it. The problem was mostly around leaks as we may have kept references on released contextual objects.

**Comment by cescoffier** [comment] 2021-02-19 09:44
BTW, if you have a better idea, PRs are more than welcome :-)

**Comment by stphngrtz** [comment] 2021-02-22 11:42
I'd love to, but with the amount of time I can spare for this, I don't see this happening in the near future.

For the application I am working on a decision has been made to go without reactive messaging for the time being, because of this _bug_. Digging deeper into it and then maybe come up with a solution would require much time and thus probably break our roadmap.

Anyway, thanks for your fast response and the great work you and your colleagues are doing.

**Comment by cescoffier** [comment] 2021-02-22 11:53
You know you can just change the channel name? The topic and the channel name can be different. 

I can't see how this is a blocker as the workaround is straightforward. 

Anyway, I will have a look to the bug.

**Comment by cescoffier** [comment] 2021-02-22 11:54
(Deleting previous comment as it was posted on the wrong issue :-))

**Comment by cescoffier** [comment] 2021-02-22 11:55
Closing issue. 

Hopefully we will have a better solution soon, but yes right now it's convoluted.

**Closed** 2021-02-22 11:54 UTC
