### ISSUE TITLE
Manual aknowledgement is not working properly on activemq

### ISSUE THREAD

**Issue by barata0** [smallrye/smallrye-reactive-messaging#126] opened 2019-06-04 00:37 UTC
## Description
The `@Acknowledgement(Strategy.MANUAL)` should prevent quarkus from automatic ACK the message.

## Actual Behaviour
The message is dequed after processed

## Expected behaviour
The message should not be dequed

## GIT
I create a git repo demonstrating the problem 
[https://github.com/barata0/quarkus-activemq-ack](https://github.com/barata0/quarkus-activemq-ack)

## Configuration
Apache-ActiveMQ version: 5.15.0
Quarkus version: 0.15.0
Quarkus Plugins:
- quarkus-smallrye-reactive-messaging
- smallrye-reactive-messaging-amqp

## Code
```
    @Incoming("my-amqp-input")
    @Acknowledgment(Strategy.MANUAL)
    public CompletionStage<Void> receive(Message<String> message) {
        String input = message.getPayload();
        logger.info("received message with payload: " + input);
        return CompletableFuture.runAsync(new DummyWorker(input));
        
        // I didn't ACK the message, but it is removed from the queue!!!
        
    }

```

**Comment by cescoffier** [comment] 2019-06-04 05:59
The issue is due to https://github.com/vert-x3/vertx-amqp-client/issues/10 which acknowledge the message for you.

**Comment by barata0** [comment] 2019-06-04 13:47
Should I close this issue?

**Comment by cescoffier** [comment] 2019-06-04 13:53
No, let's keep in open. I will work on the upstream issue soon.

**Comment by cescoffier** [comment] 2019-06-04 14:58
Upstream issue fixed ;-)

**Comment by cescoffier** [comment] 2019-06-12 15:20
Fixed in master.

**Comment by cescoffier** [comment] 2019-06-13 07:37
It does not seem to be completely fixed.

**Comment by cescoffier** [comment] 2019-06-13 08:03
This time I got it!

**Closed** 2019-06-13 08:02 UTC
