### ISSUE TITLE
Open Tracing support

### ISSUE THREAD

**Issue by iabughosh** [smallrye/smallrye-reactive-messaging#587] opened 2020-06-03 21:57 UTC
Is there a plan for including open Tracing support - like Jaeger/Kafka instruments - into reactive messaging.

**Comment by cescoffier** [comment] 2020-06-04 04:56
We are starting integrating open telemetry.

**Comment by kenfinnigan** [comment] 2020-06-04 09:48
Closing as duplicate of #562

**Closed by kenfinnigan** 2020-06-04 09:48 UTC

**Comment by iabughosh** [comment] 2020-06-04 11:42
Sorry for opening duplicate issue. I didn't now about OpenTelemetry before today :).

**Comment by kenfinnigan** [comment] 2020-06-04 12:04
Not a problem, just an issue cleanup
